# Generated by Django 5.2.5 on 2025-08-25 13:51

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-users', 'Usuários'), ('ini-cog', 'Engrenagem'), ('ini-rocket', 'Foguete'), ('ini-layers', 'Designs'), ('ini-mobile', 'Mobile'), ('ini-stats-up', 'Gráfico')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Atualização'),
        ),
    ]
