# Generated by Django 5.2.5 on 2025-08-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cargo_modificado_alter_funcionario_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-layers', 'Designs')], max_length=12, verbose_name='Icone'),
        ),
    ]
